### PR TITLE
feat: enable KromaZKTrie by default

### PR DESCRIPTION
**Pull request by jyc228**
## Summary by CodeRabbit

- **Refactor**
	- Renamed `ExperimentalZkTree` to `KromaZKTrie` across various configurations and methods to reflect the new naming convention for ZK state trie usage.
- **New Features**
	- Updated the boolean flag for ZK state trie usage to `KromaZKTrie` with a default value of `true`, enhancing user control over this feature.
- **Documentation**
	- Modified usage descriptions for related flags to better reflect their updated functionalities.

### CODE REVIEW

**Review by kangsorang — APPROVED** [review]
LGTM

**Review by 0xHansLee — COMMENTED** [review]
If you don't mind, let's use upper case for acronyms. It's preferred way in golang.
So, let's change `KromaZkTrie` to `KromaZKTrie`, all capitals. 
FYI, let's see `Initialisms` in https://go.dev/wiki/CodeReviewComments.

**Review by seolaoh — APPROVED** [review]
LGTM, I agree with the comment.

**Comment by jyc228** [comment]
@0xHansLee 
For now, I'll only reflect it in KromaZKTrie and not the rest.

**Review by 0xHansLee — APPROVED** [review]
> @0xHansLee
For now, I'll only reflect it in KromaZKTrie and not the rest.

Got it, thanks!

**Pull request merged**
