### PR TITLE
feat: change reward recipient to pre-deployed validator reward vault

### PR DESCRIPTION
**Pull request by Pangssu**

### CODE REVIEW

**Comment by chokobole** [comment]
Is this a commit to fix a bug?

**Comment by Pangssu** [comment]
> Is this a commit to fix a bug?

No. This is changes.
Is this better to be feat?

**Comment by chokobole** [comment]
> > Is this a commit to fix a bug?
> 
> No. This is changes. Is this better to be feat?

Yeap! See https://github.com/kroma-network/.github/blob/main/CONTRIBUTING.md#commit-type

**Comment by chokobole** [comment]
I think the branch can't be helped, so please just change the commit.

**Review by chokobole — APPROVED** [review]
LGTM

**Pull request merged**
